### ISSUE TITLE
Exception is happened when split version of gem packages from index.rubygems.org

### ISSUE THREAD

**Issue by poyaz** [pulp/pulp_gem#313]
**Version**
pulpcore: 3.39.21
pulp_gem: 0.5.1

**Describe the bug**
When using `pulp gem repository sync` command the below error is happend:
```
File "/usr/local/lib/python3.8/site-packages/pulpcore/tasking/tasks.py", line 61, in _execute_task
    result = func(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/pulp_gem/app/tasks/synchronizing.py", line 52, in synchronize
    dv.create()

  File "/usr/local/lib/python3.8/site-packages/pulpcore/plugin/stages/declarative_version.py", line 161, in create
    loop.run_until_complete(pipeline)

  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()

  File "/usr/local/lib/python3.8/site-packages/pulpcore/plugin/stages/api.py", line 220, in create_pipeline
    await asyncio.gather(*futures)

  File "/usr/local/lib/python3.8/site-packages/pulpcore/plugin/stages/api.py", line 41, in __call__
    await self.run()

  File "/usr/local/lib/python3.8/site-packages/pulp_gem/app/tasks/synchronizing.py", line 96, in run
    async for name, ext_versions, md5_sum in read_versions(versions_result.path):

  File "/usr/local/lib/python3.8/site-packages/pulp_gem/specs.py", line 116, in read_versions
    name, versions_str, md5_sum = line.split(" ", maxsplit=2)
```

**To Reproduce**

```
pulp gem repository create --name foo
pulp gem remote create --name gem --url https://index.rubygems.org/ --includes '{"panda":null}'
pulp gem repository sync --name foo --remote gem
```

**Expected behavior**

**Additional context**
After tracing in code and fetch all version of gem files from https://rubygems.org/versions I realized this problem happens because of `yggdrasil-engine` package.

When you fetch version of all gem package output of the **yggdrasil-engine** like that:

```
yggdrasil-engine 0.0.5.beta.11-x86_64-linux     <--------------------------------
yggdrasil-engine 0.0.5.beta.11-arm64-darwin 81a4ee4bd6870bf7d25170ab8af70df4
yggdrasil-engine 0.0.5.beta.11-x86_64-darwin b1025777074043da7e0aff6aef81bb77
yggdrasil-engine 0.0.5.beta.11-universal-java-11 6530d9f0f4e9ef4dfe39021c8f822f77
yggdrasil-engine 0.0.5.beta.11-universal-java-17 1fdd1cd2a9d6cb1d4427a7c8b17dec4c
yggdrasil-engine 0.0.5.beta.11-universal-java-1.8 c40cce75ba1c312e69ad1fc7885e17ed
```` 

Then in https://github.com/pulp/pulp_gem/blob/main/pulp_gem/specs.py#L111 function the line is split for get **name**, **version** and **checksum**. As you see the  output pf https://rubygems.org/versions returns **yggdrasil-engine 0.0.5.beta.11-x86_64-linux** line and the 3th part is missing. It is maybe a problem in gem repository but it's better to handle in code.

Solution:
1. Check length of line before split, if the array length not equal 3 then make warning and continue
2. Check length of line before split, if the array length not equal 3 then add `-` for checksum and then skip checking checksum

**Comment by mdellweg** [comment]
Thanks. Although you seem to be using an outdated version of pulp_gem, i still think it applies to main. Also, great analysis there.

**Comment by poyaz** [comment]
As i see the main branch, this snipped code is exist and problem is happened

**Comment by mdellweg** [comment]
Can you confirm my patch solves the issue you are seeing?

**Comment by poyaz** [comment]
Yeah, I has been test. It works perfectly

Thank
