### ISSUE TITLE
Update and release a compatible verson for the latest version of pulpcore

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulp_gem#85]
It would be great if users could use the existing feature set with the latest version of Pulpcore. Having this release available on PyPI would be great.

**Comment by gerrod3** [comment]
GA version compatible with latest pulpcore (3.28) as of June 27 is now available.

https://github.com/pulp/pulp_gem/releases/tag/0.1.0
https://pypi.org/project/pulp-gem/0.1.0/
